"""Общий модуль водяного знака: формат метки + движок embed/extract/locate."""

from __future__ import annotations

from app.watermark.engine import (
    EMBED_STRENGTH,
    EMBED_VERSION,
    READABLE_SCALE,
    CoarseMatch,
    EmbedResult,
    LocateMatch,
    Rebuilt,
    WatermarkEngine,
    WatermarkError,
    embed_async,
    extract_async,
    image_size,
    load_bgr,
    locate,
    locate_async,
    locate_coarse,
    locate_coarse_async,
    rebuild_fragment,
    rebuild_fragment_async,
    save_bgr,
)
from app.watermark.payload import (
    MAX_LESSON_ID,
    MAX_UID,
    PAYLOAD_VERSION,
    WM_BIT_LENGTH,
    Payload,
    bit_length,
)
from app.watermark.verify import (
    MAX_DAMAGED_BITS,
    MIN_MARGIN,
    SoftRead,
    Verdict,
    bits_of,
    decode,
    kmeans_threshold,
    match,
    near_misses,
)

__all__ = [
    "MAX_DAMAGED_BITS",
    "MAX_LESSON_ID",
    "MAX_UID",
    "MIN_MARGIN",
    "EMBED_STRENGTH",
    "EMBED_VERSION",
    "PAYLOAD_VERSION",
    "READABLE_SCALE",
    "WM_BIT_LENGTH",
    "CoarseMatch",
    "EmbedResult",
    "LocateMatch",
    "Payload",
    "Rebuilt",
    "SoftRead",
    "Verdict",
    "WatermarkEngine",
    "WatermarkError",
    "bit_length",
    "bits_of",
    "decode",
    "embed_async",
    "extract_async",
    "image_size",
    "kmeans_threshold",
    "load_bgr",
    "locate",
    "locate_async",
    "locate_coarse",
    "locate_coarse_async",
    "match",
    "near_misses",
    "rebuild_fragment",
    "rebuild_fragment_async",
    "save_bgr",
]
